/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        nexus: {
          // Dark Mode (Default - Official Theme)
          bg: '#05070A',
          'bg-soft': '#0B0D10',
          'bg-panel': '#0B0D10',
          card: 'rgba(11, 13, 16, 0.86)',
          'card-strong': 'rgba(11, 13, 16, 0.94)',
          'card-soft': 'rgba(17, 20, 25, 0.74)',
          sidebar: '#07090D',
          // Dourado e Bronze (Dark)
          gold: '#D49556',
          'gold-light': '#F2C38B',
          bronze: '#9a6a42',
          // Rose (Dark)
          rose: '#C65A71',
          'rose-light': '#E18A9D',
          'rose-dark': '#9d4e58',
          // Textos (Dark)
          text: '#f5f1ec',
          muted: '#A8A8A8',
          'muted-2': '#8f8580',
          // Status (Dark)
          success: '#7DDA6A',
          danger: '#D84B5F',
          warning: '#D89A28',
          // Bordas (Dark)
          border: 'rgba(212, 149, 86, 0.24)',
          'border-strong': 'rgba(212, 149, 86, 0.38)',
          // Light Mode (Official Premium Corporate Theme)
          'light-bg': '#F8F5F0',
          'light-bg-soft': '#F2ECE4',
          'light-bg-panel': '#F2ECE4',
          'light-card': '#FFFFFF',
          'light-card-strong': '#FFFFFF',
          'light-card-soft': '#FAF4EC',
          'light-sidebar': '#EFE6DA',
          'light-border': '#D8C5AE',
          'light-border-strong': '#C9B896',
          'light-gold': '#C48A43',
          'light-gold-light': '#D9A866',
          'light-bronze': '#8B6914',
          'light-rose': '#C65A71',
          'light-rose-light': '#D97F91',
          'light-rose-dark': '#A04A5A',
          'light-text': '#2B2B2B',
          'light-muted': '#5A5A5A',
          'light-muted-2': '#7A7A7A',
          'light-success': '#2F9E44',
          'light-danger': '#C92A2A',
          'light-warning': '#D89A28',
        },
        brand: {
          // Dashboard Image Colors (mantidos para compatibilidade)
          charcoal: '#1A1C21',
          cardDark: '#21242B',
          cardSoft: '#2A2E37',
          green: '#3E958F',
          greenHover: '#85D5D2',
          textPrimary: '#F7F2EC',
          textSecondary: 'rgba(247, 242, 236, 0.72)',
          teal: '#4DD0E1',
          purple: '#9C27B0',
          lightBg: '#F7F2EC',
          lightCard: '#FFFFFF',
          lightText: '#050505',
          lightTextSecondary: '#242424',
          borderDark: 'rgba(62, 149, 143, 0.24)',
          borderLight: 'rgba(62, 149, 143, 0.24)',
          // Compatibility aliases
          blackCherry: '#050505',
          primary: '#3E958F',
          primaryHover: '#85D5D2',
          ivorySmoke: '#F7F2EC',
          graphiteWine: '#242424',
          graphite: '#050505',
          graphiteLight: '#151515',
          pearl: '#F7F2EC',
          gold: '#D6B370',
          error: '#A94442',
        },
      },
    },
  },
  plugins: [],
};
