ALTER TABLE users ADD COLUMN company_id INT DEFAULT 1;
ALTER TABLE clients ADD COLUMN company_id INT DEFAULT 1;
ALTER TABLE products ADD COLUMN company_id INT DEFAULT 1;
ALTER TABLE suppliers ADD COLUMN company_id INT DEFAULT 1;
ALTER TABLE purchases ADD COLUMN company_id INT DEFAULT 1;
ALTER TABLE sales ADD COLUMN company_id INT DEFAULT 1;
ALTER TABLE transactions ADD COLUMN company_id INT DEFAULT 1;
ALTER TABLE appointments ADD COLUMN company_id INT DEFAULT 1;
ALTER TABLE stock_movements ADD COLUMN company_id INT DEFAULT 1;

ALTER TABLE users ADD FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE clients ADD FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE products ADD FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE suppliers ADD FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE purchases ADD FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE sales ADD FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE transactions ADD FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE appointments ADD FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE stock_movements ADD FOREIGN KEY (company_id) REFERENCES companies(id);
