ALTER TABLE clients ADD COLUMN status VARCHAR(20) DEFAULT 'ATIVO' AFTER notes;
ALTER TABLE products ADD COLUMN status VARCHAR(20) DEFAULT 'ATIVO' AFTER image;
ALTER TABLE sales ADD COLUMN status VARCHAR(20) DEFAULT 'ABERTA' AFTER total_value;
ALTER TABLE transactions ADD COLUMN status VARCHAR(20) DEFAULT 'PENDENTE' AFTER value;

CREATE INDEX idx_clients_company ON clients(company_id, active);
CREATE INDEX idx_clients_search ON clients(company_id, name, email, phone, document);
CREATE INDEX idx_products_company ON products(company_id, active);
CREATE INDEX idx_products_sku ON products(company_id, sku);
CREATE INDEX idx_sales_company ON sales(company_id);
CREATE INDEX idx_sales_created ON sales(company_id, created_at);
CREATE INDEX idx_purchases_company ON purchases(company_id);
CREATE INDEX idx_transactions_company ON transactions(company_id);
CREATE INDEX idx_transactions_date ON transactions(company_id, transaction_date);
CREATE INDEX idx_transactions_type ON transactions(company_id, type);
CREATE INDEX idx_stock_movements_product ON stock_movements(product_id, company_id);
CREATE INDEX idx_stock_movements_type ON stock_movements(company_id, type);
CREATE INDEX idx_appointments_company ON appointments(company_id);
CREATE INDEX idx_appointments_date ON appointments(company_id, appointment_date);
CREATE INDEX idx_appointments_status ON appointments(company_id, status);
CREATE INDEX idx_notifications_company ON notifications(company_id, `read`);
CREATE INDEX idx_audit_logs_company ON audit_logs(company_id, created_at);
CREATE INDEX idx_audit_logs_entity ON audit_logs(company_id, entity_type, entity_id);
CREATE INDEX idx_users_company ON users(company_id);
CREATE INDEX idx_suppliers_company ON suppliers(company_id, active);
